# approot is the base path used for links in your application
# it defaults to localhost (here http://localhost:3000)
# approot: http://mydomain:myport
port: 3000
repository_path: wikidata
repository_type: git
page_extension: .page
default_format: markdown
use_mathjax: true
feed_days: 14
use_cache: true
cache_dir: cache
front_page: Front Page
help_page: Help
max_upload_size: 1M
latex_engine: xelatex
# editors is the list of user emails which are allowed to edit pages
# leave unset to allow anyone to edit
# editors: my.email@provider.com my.other.email@example.com
